---
apiVersion: cilium.io/v2alpha1
kind: CiliumNodeConfig
metadata:
  name: single-cluster-route-for-vm-nodes
  namespace: d8-{{ .Chart.Name }}
  {{ include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  nodeSelector:
    matchLabels:
      node.deckhouse.io/virtualization-platform: "yes"
  defaults:
    single-cluster-route: "true"
